

export const products = [
    {
        id:0,
        name:"Nike Revolution 5 Runnning Trainers",
        img:"./test/shoes.png",
        price:50.00,
        size:"9",
        category:"shoes",
        subcategory:"training",
        stock:10,
        discount:0,
    },
    {
        id:1,
        name:"Men's Relaxed Fit Cargo Pant",
        img:"test/pants.png",
        price:44.00,
        size:"M",
        category:"pants",
        subcategory:"cargo",
        stock:5,
        discount:0,
    },
    {
        id:2,
        name:"Men's Classic Jersey V-Neck T-Shirt",
        img:"test/shirt.png",
        price:20.00,
        size:"M",
        category:"shirts",
        subcategory:"T-shirts",
        stock:20,
        discount:0,
    },
    {
        id:3,
        name:"Men's Slim Fit Airsoft Performance Stretch Dress Shirt",
        img:"test/shirt2.png",
        price:35.00,
        size:"XL",
        category:"shirts",
        subcategory:"dress",
        stock:3,
        discount:0,
    },
    {
        id:4,
        name:"Modern Heritage Leather Chealsea Boots",
        img:"test/shoes2.png",
        price:78.00,
        size:"10",
        category:"shoes",
        subcategory:"boots",
        stock:5,
        discount:0,
    },
    {
        id:5,
        name:"Moss Camel Tailored Fit Double Faced Overcoat",
        img:"test/jacket.png",
        price:160.00,
        size:"L",
        category:"jacket",
        subcategory:"overcoat",
        stock:1,
        discount:0.25,
    },
    {
        id:6,
        name:"Tommy Hilfiger Black Corporate Baseball Cap",
        img:"test/cap.png",
        price:45.00,
        size:"-",
        category:"accesories",
        subcategory:"cap",
        stock:10,
        discount:0,
    },
    {
        id:7,
        name:"Men's Performance Stripe Polo",
        img:"test/shirt3.png",
        price:49.50,
        size:"S",
        category:"shirts",
        subcategory:"polo",
        stock:10,
        discount:0,
    }
]


